version: '3.1'
services:
  mongo:
    build: ./mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: malvarez
      MONGO_INITDB_ROOT_PASSWORD: Trello-clone161288 
      MONGO_INITDB_DATABASE: trellodb
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - 27017:27017

    

